# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LienFund' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LienFund
pod 'Charts', '~> 3.6'
pod 'SQLite.swift', '~> 0.13.1'
end
